### ISSUE TITLE
release build issue in library 

### ISSUE THREAD

**Issue by seewah48** [BILDIT-Platform/react-native-bildit-flybuy#14]
@zeabdelkhalek - can you please take a look at it. 

Able to successfully do debug build. having issue on release builds with the latest version. below is the error am seeing in flybuy.swift class in the library.

react-native-bildit-flybuy: 0.2.3
xcode:13.1,
react-native: 0.64.2,

Error:
....../node_modules/react-native-bildit-flybuy/ios/Flybuy.swift:1:8: error: no such module 'FlyBuy'
import FlyBuy

PhaseScriptExecution [CP]\ Copy\ XCFrameworks /Users/{username}/Library/Developer/Xcode/DerivedData/BannerMobile-fdxxocqnhtdhaffemfuunwlhvzdq/Build/Intermediates.noindex/Pods.build/Release-iphonesimulator/react-native-bildit-flybuy.build/Script-5909969872634610556DC56C809DD899.sh (in target 'react-native-bildit-flybuy' from project 'Pods')
    cd /Users/{username}/Desktop/Projects/banner-mobile/ios/Pods
    /bin/sh -c   @@/Users/{username}/Library/Developer/Xcode/DerivedData/BannerMobile-fdxxocqnhtdhaffemfuunwlhvzdq/Build/Intermediates.noindex/Pods.build/Release-iphonesimulator/react-native-bildit-flybuy.build/Script-5909969872634610556DC56C809DD899.sh

warning: [CP] Unable to find matching .xcframework slice in 'ios-arm64 ios-arm64_x86_64-simulator' for the current build architectures (arm64 x86_64 i386).
warning: [CP] Unable to find matching .xcframework slice in 'ios-arm64 ios-arm64_x86_64-simulator' for the current build architectures (arm64 x86_64 i386).
warning: [CP] Unable to find matching .xcframework slice in 'ios-arm64_x86_64-simulator ios-arm64' for the current build architectures (arm64 x86_64 i386).
warning: [CP] Unable to find matching .xcframework slice in 'ios-arm64 ios-arm64_x86_64-simulator' for the current build architectures (arm64 x86_64 i386).

**Comment by mohanenm** [comment]
@zeabdelkhalek @botnerd could you take a look at this when you have some time?

**Comment by mohanenm** [comment]
@seewah48 are you targeting release and debug in your Pods? Also, are you building on an actual device or a simulator? 

The issue was not able to be reproduced on a release build.

**Comment by mohanenm** [comment]
Also, can you please try running a clean build, verifying that the dependency is referenced on the release scheme, closing Xcode completely, running pod update from the terminal, and then opening the workspace and trying once more?

**Comment by mohanenm** [comment]
@seewah48 I was able to run the sample application with react-native-bildit-flybuy: 0.2.3,
xcode:13.1, react-native: 0.64.2 without issue importing module flybuy

**Comment by mohanenm** [comment]
Running a second time, release build and getting the same error that @seewah48 got, with the example app: 
<img width="281" alt="Screen Shot 2021-11-15 at 4 50 14 PM" src="https://user-images.githubusercontent.com/20827960/141858719-d8989866-2f48-496d-b978-70514e433a7b.png">

react-native-bildit-flybuy: 0.2.3
xcode:13.1,
react-native: 0.64.2

Schemes:
<img width="926" alt="Screen Shot 2021-11-15 at 4 52 01 PM" src="https://user-images.githubusercontent.com/20827960/141858931-e12ac41b-12cf-4ba0-ba07-cef0cbe9f40e.png">

## Steps to reproduce

Follow steps on documentation:

- npm install --save react-native-bildit-flybuy

- cd ios && pod install

- Open project via workspace

- run debug build, passed. run release build, fails on import error

**Comment by zeabdelkhalek** [comment]
@mohanenm I'm getting the same error too when trying to release build in the example app, I will investigate it and let you know.

**Comment by mohanenm** [comment]
@zeabdelkhalek @seewah48 resolved by updating the framework 
<img width="880" alt="Screen Shot 2021-11-24 at 1 25 37 PM" src="https://user-images.githubusercontent.com/20827960/143294298-0dbf2484-ebc7-45e8-b1ad-dca54f56da43.png">

**Comment by addingama** [comment]
You also can fix it by changing the `Build Architecture Only` to `Yes` on the project itself.

**Comment by mohanenm** [comment]
That did not fix it for me, but can try again.

**Comment by mohanenm** [comment]
But that would make sense. Thanks for opening the PR.

**Comment by zeabdelkhalek** [comment]
@addingama @mohanenm Can we close this now?

**Comment by mohanenm** [comment]
@zeabdelkhalek We can close. 

One thing: in addition to setting the framework to build active architectures only for the release build, to do an archive you will also need to verify that the framework iOS deployment target is the same as the iOS deployment target for your build target.

**Comment by mohanenm** [comment]
closing
