### ISSUE TITLE
Multiple Dependencies with different sources

### ISSUE THREAD

**Issue by mohanenm** [BILDIT-Platform/react-native-bildit-flybuy#15]
Currently trying to build the example app in this repo and running into this error when trying to run `pod install` from the IOS folder, after running `yarn add react-native-bildit-flybuy` from the root folder. 

```
[!] There are multiple dependencies with different sources for `react-native-bildit-flybuy` in `Podfile`:

- react-native-bildit-flybuy (from `../node_modules/react-native-bildit-flybuy`)
- react-native-bildit-flybuy (from `../..`)
```

I am using: 

xcode: 13.1
react native: 0.63 
bilidt wrapper:  0.2.3

I have already tried cloning a new project, deintegrating and attempting to install pods again, remove node_modules, all to no avail.

**Comment by zeabdelkhalek** [comment]
@mohanenm If you clone this repository and you want to run the example app, you have just to run it directly without the need of running `yarn add react-native-bildit-flybuy` because it's integrated there in the Podfile

**Comment by mohanenm** [comment]
@zeabdelkhalek though this is confusing. The project stills fail in Xcode because it cannot locate the pods. If I try to disintegrate and install, I get...

```Invalid `Podfile` file: cannot load such file -- /Users/ethanmohan/Desktop/react-native-bildit-flybuy/example-app/node_modules/react-native/scripts/react_native_pods.``` 

because node_modules does not exist. 

So how would I run it without generating the node modules first?
