### ISSUE TITLE
example app build failure 

### ISSUE THREAD

**Issue by mohanenm** [BILDIT-Platform/react-native-bildit-flybuy#16]
Reopening example app build failure issue

> @mohanenm If you clone this repository and you want to run the example app, you have just to run it directly without the need of running `yarn add react-native-bildit-flybuy` because it's integrated there in the Podfile
> 
> _Originally posted by @zeabdelkhalek in https://github.com/BILDIT-Platform/react-native-bildit-flybuy/issues/15#issuecomment-970247296_
> 

@zeabdelkhalek though this is confusing. The project stills fail in Xcode because it cannot locate the pods. If I try to disintegrate and install, I get...

Invalid `Podfile` file: cannot load such file -- /Users/{username}/Desktop/react-native-bildit-flybuy/example-app/node_modules/react-native/scripts/react_native_pods.

because node_modules does not exist.

So how would I run it without generating the node modules first?

## If I run ```npm install``` generate the node modules, I get: 

``` 
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR! 
npm ERR! While resolving: react-native-bildit-flybuy-start-order-example@0.0.1
npm ERR! Found: react@16.13.1
npm ERR! node_modules/react
npm ERR!   react@"16.13.1" from the root project
npm ERR!   peer react@">=16.13.1" from react-native-permissions@3.0.4
npm ERR!   node_modules/react-native-permissions
npm ERR!     react-native-permissions@"^3.0.4" from the root project
npm ERR!   1 more (react-native)
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer react@"17.0.2" from react-native-windows@0.66.4
npm ERR! node_modules/react-native-windows
npm ERR!   peer react-native-windows@">=0.62.0" from react-native-permissions@3.0.4
npm ERR!   node_modules/react-native-permissions
npm ERR!     react-native-permissions@"^3.0.4" from the root project
npm ERR! 
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
```

I can force it or allow legacy deps, but the project app still does not build.

**Comment by zeabdelkhalek** [comment]
@mohanenm In order to run the example app please follow these steps:

1- git clone https://github.com/BILDIT-Platform/react-native-bildit-flybuy
2- cd react-native-bildit-flybuy/example-app
3- yarn install
4- cd ios && pod install

Finally open Xcode and run the app

**Comment by zeabdelkhalek** [comment]
@mohanenm In order to run the example app please follow these steps:

1- git clone https://github.com/BILDIT-Platform/react-native-bildit-flybuy
2- cd react-native-bildit-flybuy/example-app
3- yarn install
4- cd ios && pod install

Finally, open Xcode and run the app.

If you run out with a weird importing issue like the screenshot attached below, please clean the project by running: 
`npx react-native-clean-project`

<img width="906" alt="Screen Shot 2021-11-17 at 1 02 11 AM" src="https://user-images.githubusercontent.com/34510420/142085266-75eb08cc-c015-4c41-9094-f8b05e09435c.png">

**Comment by mohanenm** [comment]
Thank you. I got through that with no issues. 

However, this results in the target `React(missing)` issue after opening in Xcode discussed in #18
<img width="957" alt="Screen Shot 2021-11-16 at 7 50 42 PM" src="https://user-images.githubusercontent.com/20827960/142089332-19db2f6e-5a24-4c97-8ece-ab53965725c1.png">
