### ISSUE TITLE
create order does function does not support pickup type, pickup window, and order state, optionally

### ISSUE THREAD

**Issue by mohanenm** [BILDIT-Platform/react-native-bildit-flybuy#26]
The Flybuy SDK has the ability to set pickup type, pickup window, and order state, but they are not required. In the example app, if you do not send a pickup window, pickup type, and order state you get an error such as:
![Screen Shot 2022-01-20 at 6 20 58 PM](https://user-images.githubusercontent.com/20827960/150437676-10a15bbc-fd3e-4655-acd6-a9f8de682523.png)

I can go into the create orders call and have this work as expected by changing the behavior in the swift function, but it would be nice to have this behavior built-in. 

Further, with the current swift methods, there is no way to create an ASAP order. Even if I explicitly edit both start and end, the pickup window is caught in ```func decodePickupWindow(pickupWindow: Dictionary<String, String>?) -> PickupWindow``` because it is expecting a date. 

Making the pickup window actually optional in the framework would solve this by allowing us to leave it out and have it set to ASAP. 

cc: @AT89

**Comment by addingama** [comment]
@mohanenm can we use an empty string as the default value for pickup type and order state?

**Comment by addingama** [comment]
@mohanenm what did you change on the swift function? can you share the code changes?

**Comment by mohanenm** [comment]
@addingama yes, I can follow up a bit later, maybe tomorrow, with my changes.

**Comment by mohanenm** [comment]
> @mohanenm can we use an empty string as the default value for pickup type and order state?

an empty string would still throw an error for the pickup window though. Further, I believe that would cause unexpected behavior. I will be able to test later.

**Comment by addingama** [comment]
The `pickupType` on the RN wrapper is not used by the function, is it safe to assume we don't need it and can be removed?

![image](https://user-images.githubusercontent.com/2896774/150616892-f626fcb0-686b-49e8-a908-f59ade9cf453.png)

---------

I've checked the framework code and the `OrdersManager` have 2 `create` functions

![image](https://user-images.githubusercontent.com/2896774/150616817-1dc85500-94ff-4b01-a6b0-e44d3d3b29cf.png)

Both of them doesn't have `pickupType` parameter

---------

I can try to create another wrapper to support both of create order function.

Is that ok? @mohanenm

**Comment by mohanenm** [comment]
@addingama please leave that in. We are pushing an update out soon that will include support for pickup type in the create order on IOS.

**Comment by mohanenm** [comment]
@addingama You can leave it out for now. 

We are going to push an update soon to the iOS SDK to support this and will need to update it then, but for now we are good to leave it out.

**Comment by mohanenm** [comment]
LGTM! THX!
