### ISSUE TITLE
Support for version 2.4.1 of the Flybuy SDK

### ISSUE THREAD

**Issue by mohanenm** [BILDIT-Platform/react-native-bildit-flybuy#35]
- Adds support for BGAppRefreshTask to improve syncing on iOS 13 and higher. See [Notify SDK Documentation](https://www.radiusnetworks.com/developers/flybuy/#/sdk-2.0/notify) for details on using this.
- Support for "Defer on Pickup" Notify campaigns

**Comment by mohanenm** [comment]
Hello, any chance the most recent SDK methods could be wrapped anytime soon?

**Comment by addingama** [comment]
@mohanenm I just started working on this again. Can you share the exact documentation link for the BGAppRefreshTask and Defer on Pickup?

The link that you shared is not valid

**Comment by addingama** [comment]
Thanks @mohanenm @kriszabala

**Comment by addingama** [comment]
The latest release has version 2.6.3
