### ISSUE TITLE
react-natvie buildit- fly-buy issue

### ISSUE THREAD

**Issue by lavarajupdl** [BILDIT-Platform/react-native-bildit-flybuy#37]
<img width="852" alt="Screenshot 2022-04-25 at 2 53 03 PM" src="https://user-images.githubusercontent.com/103950384/165060891-cf056949-15c4-401a-b155-ed1065b7a313.png">

**Comment by addingama** [comment]
@lavarajupdl Can you share your machine info and a repo for reproduction?

- XCode version
- Mac processor
- React Native Version

Did you try to run the sample app inside the library?

**Comment by addingama** [comment]
@lavarajupdl I've tried running the sample app locally and it can be built without issue on iOS.

Please try changing the target simulator to iPhone or iPad

**Comment by addingama** [comment]
No
