### ISSUE TITLE
Support for version 2.6 of the Flybuy SDK

### ISSUE THREAD

**Issue by mohanenm** [BILDIT-Platform/react-native-bildit-flybuy#42]
Hello FB just released a new version of the SDK!

[SDK Release](https://github.com/RadiusNetworks/flybuy-ios)
[SDK Release Notes](https://github.com/RadiusNetworks/flybuy-ios/releases/tag/2.6.0)
[Pertinent Docs](https://www.radiusnetworks.com/developers/flybuy/#/sdk-2.0/pickup/050-order-creation-flow?id=fetch-site-by-partner-identifier)

If you all could update, that would be great! Thank You!

**Comment by mohanenm** [comment]
cc: @addingama @zeabdelkhalek

**Comment by mohanenm** [comment]
Now version 2.6.1, thank you!

**Comment by addingama** [comment]
https://github.com/BILDIT-Platform/react-native-bildit-flybuy/pull/44
