### ISSUE TITLE
Fetch Order with Redemption Code

### ISSUE THREAD

**Issue by mjosipovic** [BILDIT-Platform/react-native-bildit-flybuy#5]
Hello, many thanks for the repository. Do you have plan to support method to fetch the order using the redemption code?

**Comment by BILDIT-LLC** [comment]
@zeabdelkhalek will add it. Or you can PR your changes from the fork.

**Comment by zeabdelkhalek** [comment]
We have @david-netizen working on that right now.

**Comment by mjosipovic** [comment]
Thank you very much. All the best for the  whole team.   From: Zellat AbdelkhalekSent: 14. lipnja 2021. 4:31To: BILDIT-Platform/react-native-bildit-flybuyCc: mjosipovic; AuthorSubject: Re: [BILDIT-Platform/react-native-bildit-flybuy] Fetch Order with Redemption Code (#5) Closed #5.—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.
