### ISSUE TITLE
react-native-bildit-flybuy:compileDebugKotlin

### ISSUE THREAD

**Issue by mohanenm** [BILDIT-Platform/react-native-bildit-flybuy#54]
**Describe the bug**
Version of react native 0.6.4.2
Version of react native wrapper 2.1.1

When trying to build android app, developer is running into this error: 

```
Execution failed for task ':react-native-bildit-flybuy:compileDebugKotlin'.
> A failure occurred while executing org.jetbrains.kotlin.compilerRunner.GradleCompilerRunnerWithWorkers$GradleKotlinCompilerWorkAction
> Compilation error. See log for more details
```

**Comment by mohanenm** [comment]
@pranaynemavrize

**Comment by mohanenm** [comment]
@addingama we have looked around to see what might be causing this, but nothing is jumping out as the correct solution. Anything we can do to help troubleshoot here?

**Comment by addingama** [comment]
@mohanenm I am not sure too, but the React Native `0.64.*` is no longer supported by the Official RN.

Maybe try to upgrade the project to at least `0.69.x`

**Comment by mohanenm** [comment]
Thank you @addingama 

@pranaynemavrize ^^

**Comment by pranaynemavrize** [comment]
@addingama @mohanenm  as of now we cant upgrade RN to 0.69 , as it will require more regression and testing and dev work.

So can you suggest some alternatives ?

**Comment by mohanenm** [comment]
Would using a different version of the wrapper(one that did not have this problem) and updating the flybuy SDK version manually be the best option in this case @addingama

**Comment by pranaynemavrize** [comment]
@mohanenm even if we try to upgrade android native (not wrapper) still facing same issue

**Comment by pranaynemavrize** [comment]
[build.gradle.zip](https://github.com/BILDIT-Platform/react-native-bildit-flybuy/files/12369097/build.gradle.zip)
attaching build gradle file for referance

**Comment by mohanenm** [comment]
@addingama this seems related: https://github.com/segmentio/analytics-react-native/issues/225

**Comment by mohanenm** [comment]
try: 

1: Add a String to android/build.gradle

kotlinVersion = "1.8.10"

2: Delete node_modules folder

rm -r node_modules

3:npm i

4:npx react-native run-android

**Comment by addingama** [comment]
@pranaynemavrize what is the recently working version of `react-native-bildit-flybuy` that working with your project?

This library automatically use kotlin `1.5.30` but it can be override by adding `kotlinVersion` on `android/build.gradle`

This is on the example app.

```
buildscript {
    ext {
        buildToolsVersion = "33.0.0"
        minSdkVersion = 21
        compileSdkVersion = 33
        targetSdkVersion = 33
        kotlinVersion = "1.6.0"
    }
   // the rest of the content
}
```

Then you can try to build it again.

**Comment by pranaynemavrize** [comment]
working version of react-native-bildit-flybuy is 1.0.4

**Comment by pranaynemavrize** [comment]
@addingama

**Comment by addingama** [comment]
@pranaynemavrize please try add the `kotlinVersion` and use `1.6.0` or `1.7.10` and share the result.

**Comment by mohanenm** [comment]
@pranaynemavrize ^

**Comment by mohanenm** [comment]
Able to run using kotlin 1.6.0
