### ISSUE TITLE
Error compiling on Kotlin 1.8

### ISSUE THREAD

**Issue by keithyoder** [BILDIT-Platform/react-native-bildit-flybuy#62]
ItsPleinAir has reported errors trying to build their app.

Is this an issue using more recent Kotlin verions?

![image](https://github.com/BILDIT-Platform/react-native-bildit-flybuy/assets/5786954/2a797bd5-e520-4638-ae01-8111e9c44054)

**Comment by keithyoder** [comment]
Confirmed IPA is building with Kotlin 1.8.

**Comment by addingama** [comment]
Thanks for the info, the latest kotlin version has more strict checking.

@keithyoder can you provide the kotlin version that failing?

**Comment by keithyoder** [comment]
https://github.com/BILDIT-Platform/react-native-bildit-flybuy/blob/7b88e4c34247306dce8d61b82e52fe7b70ed7efe/android/src/main/java/com/reactnativeflybuy/Util.kt#L7-L23

```kotlin
fun handleFlyBuyError(sdkError: SdkError?) { 
   when (sdkError?.type) { 
     ResponseEventType.NO_CONNECTION -> { 
       Log.e("FlyBuy SDK Error", "No Connection") 
     } 
     ResponseEventType.FAILED -> { 
       when (sdkError.code) { 
         425 -> { 
           Log.e("FlyBuy SDK Error", "Upgrade your app!") 
         } 
         else -> { 
           Log.e("FlyBuy SDK Error", sdkError.userError()) 
         } 
       } 
     }
    else -> {
      // nothing to do.
    } 
   } 
 } 
```

**Comment by keithyoder** [comment]
https://github.com/BILDIT-Platform/react-native-bildit-flybuy/blob/7b88e4c34247306dce8d61b82e52fe7b70ed7efe/android/src/main/java/com/reactnativeflybuy/FlybuyModule.kt#L696

```kotlin
 map.putInt("siteID", order.site?.id!!) 
```

I think this is okay since any order has to have a site.

**Comment by wilsolutions** [comment]
I am planning to upgrade to RN 0.72 and and ended up running into Kotlin version issues as well.

```
> Task :react-native-bildit-flybuy:compileDebugKotlin FAILED
'compileDebugJavaWithJavac' task (current target is 11) and 'compileDebugKotlin' task (current target is 1.8) jvm target compatibility should be set to the same Java version.
```

Please, do we have any idea when we may have a release bumping Kotlin?

Thanks

**Comment by addingama** [comment]
@wilsolutions  do you set any kotlin version in your build.gradle file?

**Comment by addingama** [comment]
@wilsolutions can you try using version `2.1.5` and send `kotlinVersion = '1.8.0'`?

**Comment by wilsolutions** [comment]
> @wilsolutions can you try using version `2.1.5` and send `kotlinVersion = '1.8.0'`?

I will need to revisit this later, I was exploring the possibility of migrating a RN 0.70 App to RN 0.72 when I've found this issue, it will take me a few weeks until I'm able to look at this again...

But I did bump my project to the `2.1.5` version with RN 0.70 and kotlin 1.6.0 and I have no issues.

**Comment by addingama** [comment]
I'll close this issue for now. I've tested the latest version with kotlin 1.8.0 and it's working.
