### ISSUE TITLE
Feature request: Flybuy module per configuration

### ISSUE THREAD

**Issue by wilsolutions** [BILDIT-Platform/react-native-bildit-flybuy#65]
**Describe the bug**
Currently the react-native-bildit-flybuy includes all Flybuy modules eg: Presence/notify
`s.vendored_frameworks = 'ios/Frameworks/FlyBuy.xcframework', 'ios/Frameworks/FlyBuyPickup.xcframework', 'ios/Frameworks/FlyBuyNotify.xcframework', 'ios/Frameworks/FlyBuyPresence.xcframework'
`
This will result in rejection from the Apple Store review after submitting an App that doesn't use one of these modules. 
For example an App that only use Pickup, will be rejected because the Presence framework is present in the App even though the User is not using this module.

**To Reproduce**
Setup an App with only FlyBuy.Core.configure(your_token) and FlyBuy.Pickup.configure() and submit for Apple approval.

**Expected behavior**
App shouldn't be rejected 

**Additional context**
A solution for this would be to only add the Presence module (or other module) based on configuration so that it won't be shipped with the App.

A few approaches that came to my head are:
- Have a configuration file that will only add the modules that are going to be used.
Or 
- Instruct the Users to manually remove the ones they are not going to use (this is what I did in order to pass Apple approval)

**Comment by zeabdelkhalek** [comment]
AFAIK React Native currently doesn't support dynamically linking native modules out of the box. so the current solution that I have in my mind is to use subspecs and the user will manually add the specs that he want to use in his Podfile.

**Comment by addingama** [comment]
I'll close this issue, the latest version now support module separation
