### ISSUE TITLE
'Could not build Objective-C module 'react_native_bildit_flybuy'., "unsupported Swift architecture" 

### ISSUE THREAD

**Issue by sangamivivek** [BILDIT-Platform/react-native-bildit-flybuy#71]
**Describe the bug**
Encountering the error 'Could not build Objective-C module 'react_native_bildit_flybuy'., "unsupported Swift architecture" on iOS after updating to version 2.3.1 of the wrapper.

**To Reproduce**

    "react": "18.2.0",
    "react-native": "0.71.19",
    "react-native-bildit-flybuy": "^2.3.1",
    
    Run app on Xcode

**Screenshots**
<img width="810" alt="Screenshot 2024-05-22 at 8 57 21 PM" src="https://github.com/BILDIT-Platform/react-native-bildit-flybuy/assets/63785243/06b7ff21-1626-45ee-a702-6d023947e7c8">

@mohanenm

**Comment by sangamivivek** [comment]
@mohanenm I have followed the suggested steps. The error still persists.

**Comment by sangamivivek** [comment]
@mohanenm Its 15.4

**Comment by sangamivivek** [comment]
@mohanenm 

We have tried multiple approaches to resolve the issue on iOS, including cleaning and rebuilding the project, verifying the Xcode project settings, deployment target, and architecture settings. Here are some details about the environment:
Xcode: 15.4
CocoaPods: 1.15.2
React Native: 0.71.19
Despite these efforts, the issue persists. The 'react_native_bildit_flybuy' wrapper version 2.1.3 works perfectly, but we encounter this error when upgrading to version 2.3.1. Is there anything we need to change to support the latest version of the wrapper?

**Comment by sangamivivek** [comment]
@wesleyguirra Thanks for your suggestion. I've tried building the app on a real device and it works fine. However the issue still persists on the simulator, even after removing 'arm64' from Excluded Architectures in Xcode. Below is the snippet of our Podfile:

```
  post_install do |installer|
    installer.pods_project.targets.each do |target|
      target.build_configurations.each do |config|
        config.build_settings["ONLY_ACTIVE_ARCH"] = "NO"
      end
    end
    # flipper_post_install(installer)
    react_native_post_install(
      installer,
      # Set `mac_catalyst_enabled` to `true` in order to apply patches
      # necessary for Mac Catalyst builds
      :mac_catalyst_enabled => false
    )
    __apply_Xcode_12_5_M1_post_install_workaround(installer)
  end
```

Do you have any other suggestions or insights on what might be causing this issue on the simulator?

**Comment by wesleyguirra** [comment]
@sangamivivek try removing all post install just to see what happens, so we can track down the issue

**Comment by sangamivivek** [comment]
Removing these post install instructions are impacting other sdks
RCT Folly: No template named 'unary_function' in namespace 'std'; did you mean '__unary_function'?
struct hash_base : std::unary_function<T, std::size_t> {};
fixing this leads to other errors on Firebase SDK 
Pods/Firebase/CoreOnly/Sources/Firebase.h:42:13 Could not build module 'FirebaseDatabase' 
FirebaseDatabase.framework/Headers/FirebaseDatabase-Swift.h:313:2 Unsupported Swift architecture

**Comment by wesleyguirra** [comment]
@sangamivivek #76 may fix it, you should keep:

```ruby
config.build_settings["EXCLUDED_ARCHS[sdk=iphonesimulator*]"] = 'arm64'
```

Check the `development-app` Podfile in that branch, also can you try installing the library from that branch before I created a new release?

**Comment by sangamivivek** [comment]
@wesleyguirra I have installed library from that branch and it works, even without adding "config.build_settings["EXCLUDED_ARCHS[sdk=iphonesimulator*]"]" to our config file.

Let us know once you the new version is available

**Comment by sangamivivek** [comment]
@wesleyguirra any update on the new version release with this fix?

**Comment by wesleyguirra** [comment]
@sangamivivek latest release should fix this, can you test and tell me if it works for you, I'm closing it for now, don't be afraid to reopen if you have any issues
