### ISSUE TITLE
redeemedAt differences on IOS and Android 

### ISSUE THREAD

**Issue by mohanenm** [BILDIT-Platform/react-native-bildit-flybuy#89]
`redeemedAt` is null on iOS and “null” (string) on Android on fetch unclaimed order calls. This results in having to handle responses differently based on platform.

**Comment by addingama** [comment]
@mohanenm is this on the latest wrapper?

**Comment by botnerd** [comment]
@addingama please stand by on this. we're discussing how this needs to be fixed and will let you know.

**Comment by botnerd** [comment]
@addingama what are our options on this to get iOS and Android to match types for `redeemedAt`?

**Comment by addingama** [comment]
@botnerd @mohanenm I've created a PR for this and it should be available on version `2.20.8`
