### ISSUE TITLE
Misspelling of `spotIdentifier` field on `Order`

### ISSUE THREAD

**Issue by botnerd** [BILDIT-Platform/react-native-bildit-flybuy#92]
The `spotIdentifier` field on the order is misspelled as `spotIdentifer`. In order to fix without breaking apps using the wrapper when upgrading, add a new `spotIdentifier` field and deprecate the misspelled `spotIdentifer`.

**Comment by addingama** [comment]
@botnerd The fix can't be done from the native side

![CleanShot 2024-09-11 at 16 43 48@2x](https://github.com/user-attachments/assets/e427ba2f-4e5a-41c7-9fc4-24cad3f3ffc6)

the typescript type is correct, it's expecting `spotIdentifier` 

![CleanShot 2024-09-11 at 16 45 40@2x](https://github.com/user-attachments/assets/11169a80-fde6-4f8b-9050-590b0a56615f)

The changes needed should be updating the SDK to expose the correct attribute
